### PR TITLE
Allow mods to replace assets

### PR DESCRIPTION
**Pull request by Gingeh**
Assets from mods will now replace base assets if they have the same name.

image
image

I've tested this for a model, map, texture and font.
(the other asset types are unchanged)

### CODE REVIEW

**Comment by jasminegamedev** [comment]
This makes sense to me. I think this won't support replacing dialog or audio currently, since those work a bit differently. Do you think that's something we should look into as well? I could see replacing dialog being useful particularly for like, translation mods.
Other than that, I think this looks good to me.

**Comment by Gingeh** [comment]
Dialogue replacement seems to already work without any changes (because custom dialogue is loaded last)
image

I haven't tested audio replacement (I don't have fmod), but  `Audio.LoadBank` overwrites data with identical paths so it may already work without changes?

**Comment by jasminegamedev** [comment]
Oh, nice! I hadn't looked into it, so was just guessing. I'll review this a bit more later and merge it in if it looks good.

**Comment by jasminegamedev** [comment]
I think we might want to holdoff on this. there's another pull request with some pretty heavy refactors that I think will conflict with this. We might need to end up doing this a bit differently.
https://github.com/jasminegamedev/Fuji/pull/3/files
But if your change doesn't get in, I'll try to make sure there's still a way to do asset replacing

**Comment by Gingeh** [comment]
Closing this for now, we can start it anew once we have a proper plan for the asset system

**Pull request closed without merging**
